// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306145313_update user entity")]
    partial class updateuserentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Acl.Entities.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_permission");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_role_permission_branch_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_permission_role_id");

                    b.ToTable("role_permission", "acl");
                });

            modelBuilder.Entity("Base.Entities.Branch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("BranchType")
                        .HasColumnType("integer")
                        .HasColumnName("branch_type");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_no");

                    b.Property<decimal>("CurrentLoad")
                        .HasColumnType("numeric")
                        .HasColumnName("current_load");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("text")
                        .HasColumnName("operating_hours");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal?>("StorageCapacity")
                        .HasColumnType("numeric")
                        .HasColumnName("storage_capacity");

                    b.HasKey("Id")
                        .HasName("pk_branch");

                    b.ToTable("branch", "Base");
                });

            modelBuilder.Entity("Base.Entities.BranchPinCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pin_code");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_branch_pin_code");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_branch_pin_code_branch_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_branch_pin_code_rec_by_id");

                    b.ToTable("branch_pin_code", "Base");
                });

            modelBuilder.Entity("Base.Entities.Organization", b =>
                {
                    b.Property<string>("ItemKey")
                        .HasColumnType("text")
                        .HasColumnName("item_key");

                    b.Property<string>("ItemValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_value");

                    b.HasKey("ItemKey")
                        .HasName("pk_organization_info");

                    b.ToTable("organization_info", "Base");
                });

            modelBuilder.Entity("Base.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("Priority")
                        .HasColumnType("bigint")
                        .HasColumnName("priority");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_role_branch_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_role_rec_by_id");

                    b.ToTable("role", "acl");
                });

            modelBuilder.Entity("Base.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<int>("UserLevel")
                        .HasColumnType("integer")
                        .HasColumnName("user_level");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_user_branch_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_created_by_id");

                    b.ToTable("user", "Base");
                });

            modelBuilder.Entity("Base.Entities.UserBranchTransfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromBranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_branch_id");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("RequestInitiatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("request_initiator_id");

                    b.Property<string>("RequestNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_note");

                    b.Property<DateTime>("RequestSentOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("request_sent_on");

                    b.Property<long?>("ResponderId")
                        .HasColumnType("bigint")
                        .HasColumnName("responder_id");

                    b.Property<string>("ResponseNote")
                        .HasColumnType("text")
                        .HasColumnName("response_note");

                    b.Property<DateTime?>("ResponseOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("response_on");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("ToBranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_branch_id");

                    b.Property<int>("TransferStatus")
                        .HasColumnType("integer")
                        .HasColumnName("transfer_status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_branch_transfer");

                    b.HasIndex("FromBranchId")
                        .HasDatabaseName("ix_user_branch_transfer_from_branch_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_user_branch_transfer_rec_by_id");

                    b.HasIndex("RequestInitiatorId")
                        .HasDatabaseName("ix_user_branch_transfer_request_initiator_id");

                    b.HasIndex("ResponderId")
                        .HasDatabaseName("ix_user_branch_transfer_responder_id");

                    b.HasIndex("ToBranchId")
                        .HasDatabaseName("ix_user_branch_transfer_to_branch_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_branch_transfer_user_id");

                    b.ToTable("UserBranchTransfer", "Base");
                });

            modelBuilder.Entity("Base.Entities.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_role");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_user_role_branch_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_user_role_rec_by_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_role_user_id");

                    b.ToTable("user_role", "acl");
                });

            modelBuilder.Entity("Acl.Entities.RolePermission", b =>
                {
                    b.HasOne("Base.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_branch_branch_id");

                    b.HasOne("Base.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_role_role_id");

                    b.Navigation("Branch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Base.Entities.BranchPinCode", b =>
                {
                    b.HasOne("Base.Entities.Branch", "Branch")
                        .WithMany("PinCodes")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_branch_pin_code_branch_branch_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_branch_pin_code_user_rec_by_id");

                    b.Navigation("Branch");

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("Base.Entities.Role", b =>
                {
                    b.HasOne("Base.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_branch_branch_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_rec_by_id");

                    b.Navigation("Branch");

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("Base.Entities.User", b =>
                {
                    b.HasOne("Base.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_branch_id");

                    b.HasOne("Base.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_user_created_by_id");

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Base.Entities.UserBranchTransfer", b =>
                {
                    b.HasOne("Base.Entities.Branch", "FromBranch")
                        .WithMany()
                        .HasForeignKey("FromBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_transfer_branch_from_branch_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_transfer_user_rec_by_id");

                    b.HasOne("Base.Entities.User", "RequestInitiator")
                        .WithMany()
                        .HasForeignKey("RequestInitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_transfer_user_request_initiator_id");

                    b.HasOne("Base.Entities.User", "Responder")
                        .WithMany()
                        .HasForeignKey("ResponderId")
                        .HasConstraintName("fk_user_branch_transfer_user_responder_id");

                    b.HasOne("Base.Entities.Branch", "ToBranch")
                        .WithMany()
                        .HasForeignKey("ToBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_transfer_branch_to_branch_id");

                    b.HasOne("Base.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_transfer_user_user_id");

                    b.Navigation("FromBranch");

                    b.Navigation("RecBy");

                    b.Navigation("RequestInitiator");

                    b.Navigation("Responder");

                    b.Navigation("ToBranch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Base.Entities.UserRole", b =>
                {
                    b.HasOne("Base.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_branch_branch_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_rec_by_id");

                    b.HasOne("Base.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_role_id");

                    b.HasOne("Base.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_user_id");

                    b.Navigation("Branch");

                    b.Navigation("RecBy");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Base.Entities.Branch", b =>
                {
                    b.Navigation("PinCodes");
                });

            modelBuilder.Entity("Base.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
