// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331033510_AddPickupTask")]
    partial class AddPickupTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Acl.Entities.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_permission");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_role_permission_branch_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_permission_role_id");

                    b.ToTable("role_permission", "acl");
                });

            modelBuilder.Entity("Base.Entities.Branch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("BranchType")
                        .HasColumnType("integer")
                        .HasColumnName("branch_type");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_no");

                    b.Property<decimal>("CurrentLoad")
                        .HasColumnType("numeric")
                        .HasColumnName("current_load");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("text")
                        .HasColumnName("operating_hours");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal?>("StorageCapacity")
                        .HasColumnType("numeric")
                        .HasColumnName("storage_capacity");

                    b.HasKey("Id")
                        .HasName("pk_branch");

                    b.ToTable("branch", "Base");
                });

            modelBuilder.Entity("Base.Entities.BranchPinCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pin_code");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_branch_pin_code");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_branch_pin_code_branch_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_branch_pin_code_rec_by_id");

                    b.ToTable("branch_pin_code", "Base");
                });

            modelBuilder.Entity("Base.Entities.Consignment.Consignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actual_delivery_date");

                    b.Property<decimal>("ChargeableWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("chargeable_weight");

                    b.Property<decimal?>("CodAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("cod_amount");

                    b.Property<decimal?>("DeclaredValue")
                        .HasColumnType("numeric")
                        .HasColumnName("declared_value");

                    b.Property<long>("DestinationBranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_branch_id");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expected_delivery_date");

                    b.Property<long>("OriginBranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_branch_id");

                    b.Property<int>("PackageCount")
                        .HasColumnType("integer")
                        .HasColumnName("package_count");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("integer")
                        .HasColumnName("payment_mode");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("ReceiverAddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("receiver_address_id");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint")
                        .HasColumnName("receiver_id");

                    b.Property<long>("SenderAddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_address_id");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_id");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("service_type");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("text")
                        .HasColumnName("special_instructions");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("total_volume");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("total_weight");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tracking_number");

                    b.Property<decimal>("VolumetricWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("volumetric_weight");

                    b.HasKey("Id")
                        .HasName("pk_consignment");

                    b.HasIndex("DestinationBranchId")
                        .HasDatabaseName("ix_consignment_destination_branch_id");

                    b.HasIndex("OriginBranchId")
                        .HasDatabaseName("ix_consignment_origin_branch_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_consignment_rec_by_id");

                    b.HasIndex("ReceiverAddressId")
                        .HasDatabaseName("ix_consignment_receiver_address_id");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_consignment_receiver_id");

                    b.HasIndex("SenderAddressId")
                        .HasDatabaseName("ix_consignment_sender_address_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_consignment_sender_id");

                    b.HasIndex("TrackingNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_consignment_tracking_number");

                    b.ToTable("consignment", "consignment");
                });

            modelBuilder.Entity("Base.Entities.Consignment.ConsignmentStatusLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConsignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("consignment_id");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("StatusType")
                        .HasColumnType("integer")
                        .HasColumnName("status_type");

                    b.HasKey("Id")
                        .HasName("pk_consignment_status_log");

                    b.HasIndex("ConsignmentId")
                        .HasDatabaseName("ix_consignment_status_log_consignment_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_consignment_status_log_rec_by_id");

                    b.ToTable("consignment_status_log", "consignment");
                });

            modelBuilder.Entity("Base.Entities.Consignment.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CustomerType")
                        .HasColumnType("integer")
                        .HasColumnName("customer_type");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_no");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<string>("SecondaryPhoneNo")
                        .HasColumnType("text")
                        .HasColumnName("secondary_phone_no");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_customer_rec_by_id");

                    b.ToTable("customer", "consignment");
                });

            modelBuilder.Entity("Base.Entities.Consignment.CustomerAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<int>("AddressType")
                        .HasColumnType("integer")
                        .HasColumnName("address_type");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("ContactNo")
                        .HasColumnType("text")
                        .HasColumnName("contact_no");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Landmark")
                        .HasColumnType("text")
                        .HasColumnName("landmark");

                    b.Property<string>("Latitude")
                        .HasColumnType("text")
                        .HasColumnName("latitude");

                    b.Property<string>("Longitude")
                        .HasColumnType("text")
                        .HasColumnName("longitude");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pin_code");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_customer_address");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_address_customer_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_customer_address_rec_by_id");

                    b.ToTable("customer_address", "consignment");
                });

            modelBuilder.Entity("Base.Entities.Consignment.Package", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<bool>("CanBeStacked")
                        .HasColumnType("boolean")
                        .HasColumnName("can_be_stacked");

                    b.Property<long>("ConsignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("consignment_id");

                    b.Property<string>("ContentDescription")
                        .HasColumnType("text")
                        .HasColumnName("content_description");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric")
                        .HasColumnName("height");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fragile");

                    b.Property<bool>("IsHazardous")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hazardous");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric")
                        .HasColumnName("length");

                    b.Property<int>("PackageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("package_number");

                    b.Property<int>("PackageType")
                        .HasColumnType("integer")
                        .HasColumnName("package_type");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<bool>("RequiresColdChain")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_cold_chain");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.Property<decimal>("VolumetricWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("volumetric_weight");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_package");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_package_barcode");

                    b.HasIndex("ConsignmentId")
                        .HasDatabaseName("ix_package_consignment_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_package_rec_by_id");

                    b.ToTable("package", "consignment");
                });

            modelBuilder.Entity("Base.Entities.Consignment.PickupTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignedDriverId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_driver_id");

                    b.Property<long?>("AssignedVehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_vehicle_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<long>("ConsignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("consignment_id");

                    b.Property<string>("ContactName")
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<int?>("FailReason")
                        .HasColumnType("integer")
                        .HasColumnName("fail_reason");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pickup_address");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("pickup_date");

                    b.Property<int>("PickupSlot")
                        .HasColumnType("integer")
                        .HasColumnName("pickup_slot");

                    b.Property<DateTime?>("PickupTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("pickup_time");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TaskStatus")
                        .HasColumnType("integer")
                        .HasColumnName("task_status");

                    b.Property<decimal?>("VerifiedWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("verified_weight");

                    b.HasKey("Id")
                        .HasName("pk_pickup_task");

                    b.HasIndex("AssignedDriverId")
                        .HasDatabaseName("ix_pickup_task_assigned_driver_id");

                    b.HasIndex("AssignedVehicleId")
                        .HasDatabaseName("ix_pickup_task_assigned_vehicle_id");

                    b.HasIndex("ConsignmentId")
                        .HasDatabaseName("ix_pickup_task_consignment_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_pickup_task_rec_by_id");

                    b.ToTable("pickup_task", "consignment");
                });

            modelBuilder.Entity("Base.Entities.Driver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("LicenseExpiry")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("license_expiry");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_number");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_driver");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_driver_employee_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_driver_rec_by_id");

                    b.ToTable("driver", "Base");
                });

            modelBuilder.Entity("Base.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AlternatePhone")
                        .HasColumnType("text")
                        .HasColumnName("alternate_phone");

                    b.Property<long>("CurrentBranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_branch_id");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Designation")
                        .HasColumnType("text")
                        .HasColumnName("designation");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_code");

                    b.Property<int>("EmployeeStatus")
                        .HasColumnType("integer")
                        .HasColumnName("employee_status");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("integer")
                        .HasColumnName("employee_type");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("joining_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("termination_date");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_employee");

                    b.HasIndex("CurrentBranchId")
                        .HasDatabaseName("ix_employee_current_branch_id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_employee_code");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_employee_rec_by_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_user_id")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("employee", "Base");
                });

            modelBuilder.Entity("Base.Entities.Organization", b =>
                {
                    b.Property<string>("ItemKey")
                        .HasColumnType("text")
                        .HasColumnName("item_key");

                    b.Property<string>("ItemValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_value");

                    b.HasKey("ItemKey")
                        .HasName("pk_organization_info");

                    b.ToTable("organization_info", "Base");
                });

            modelBuilder.Entity("Base.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("Priority")
                        .HasColumnType("bigint")
                        .HasColumnName("priority");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_role_branch_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_role_rec_by_id");

                    b.ToTable("role", "acl");
                });

            modelBuilder.Entity("Base.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<int>("UserLevel")
                        .HasColumnType("integer")
                        .HasColumnName("user_level");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_user_branch_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_created_by_id");

                    b.ToTable("user", "Base");
                });

            modelBuilder.Entity("Base.Entities.UserBranchTransfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromBranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_branch_id");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("RequestInitiatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("request_initiator_id");

                    b.Property<string>("RequestNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_note");

                    b.Property<DateTime>("RequestSentOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("request_sent_on");

                    b.Property<long?>("ResponderId")
                        .HasColumnType("bigint")
                        .HasColumnName("responder_id");

                    b.Property<string>("ResponseNote")
                        .HasColumnType("text")
                        .HasColumnName("response_note");

                    b.Property<DateTime?>("ResponseOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("response_on");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("ToBranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_branch_id");

                    b.Property<int>("TransferStatus")
                        .HasColumnType("integer")
                        .HasColumnName("transfer_status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_branch_transfer");

                    b.HasIndex("FromBranchId")
                        .HasDatabaseName("ix_user_branch_transfer_from_branch_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_user_branch_transfer_rec_by_id");

                    b.HasIndex("RequestInitiatorId")
                        .HasDatabaseName("ix_user_branch_transfer_request_initiator_id");

                    b.HasIndex("ResponderId")
                        .HasDatabaseName("ix_user_branch_transfer_responder_id");

                    b.HasIndex("ToBranchId")
                        .HasDatabaseName("ix_user_branch_transfer_to_branch_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_branch_transfer_user_id");

                    b.ToTable("UserBranchTransfer", "Base");
                });

            modelBuilder.Entity("Base.Entities.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_role");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_user_role_branch_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_user_role_rec_by_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_role_user_id");

                    b.ToTable("user_role", "acl");
                });

            modelBuilder.Entity("Base.Entities.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CurrentBranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_branch_id");

                    b.Property<int>("FuelType")
                        .HasColumnType("integer")
                        .HasColumnName("fuel_type");

                    b.Property<bool>("HasColdStorage")
                        .HasColumnType("boolean")
                        .HasColumnName("has_cold_storage");

                    b.Property<DateTime>("InsuranceExpiry")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insurance_expiry");

                    b.Property<DateTime?>("LastServiceDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_service_date");

                    b.Property<decimal>("MaxVolumeCapacity")
                        .HasColumnType("numeric")
                        .HasColumnName("max_volume_capacity");

                    b.Property<decimal>("MaxWeightCapacity")
                        .HasColumnType("numeric")
                        .HasColumnName("max_weight_capacity");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("integer")
                        .HasColumnName("ownership_type");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("SupportsFragile")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_fragile");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_number");

                    b.Property<int>("VehicleStatus")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_status");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id")
                        .HasName("pk_vehicle");

                    b.HasIndex("CurrentBranchId")
                        .HasDatabaseName("ix_vehicle_current_branch_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_vehicle_rec_by_id");

                    b.ToTable("vehicle", "Base");
                });

            modelBuilder.Entity("Base.Entities.VehicleAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AssignedFrom")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_from");

                    b.Property<DateTime?>("AssignedTo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_to");

                    b.Property<int>("AssignmentType")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_type");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("RecById")
                        .HasColumnType("bigint")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("TripId")
                        .HasColumnType("bigint")
                        .HasColumnName("trip_id");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_assignment");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_vehicle_assignment_employee_id");

                    b.HasIndex("RecById")
                        .HasDatabaseName("ix_vehicle_assignment_rec_by_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_vehicle_assignment_vehicle_id");

                    b.ToTable("vehicle_assignment", "Base");
                });

            modelBuilder.Entity("Acl.Entities.RolePermission", b =>
                {
                    b.HasOne("Base.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_branch_branch_id");

                    b.HasOne("Base.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_role_role_id");

                    b.Navigation("Branch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Base.Entities.BranchPinCode", b =>
                {
                    b.HasOne("Base.Entities.Branch", "Branch")
                        .WithMany("PinCodes")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_branch_pin_code_branch_branch_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_branch_pin_code_user_rec_by_id");

                    b.Navigation("Branch");

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("Base.Entities.Consignment.Consignment", b =>
                {
                    b.HasOne("Base.Entities.Branch", "DestinationBranch")
                        .WithMany()
                        .HasForeignKey("DestinationBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consignment_branch_destination_branch_id");

                    b.HasOne("Base.Entities.Branch", "OriginBranch")
                        .WithMany()
                        .HasForeignKey("OriginBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consignment_branch_origin_branch_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consignment_user_rec_by_id");

                    b.HasOne("Base.Entities.Consignment.CustomerAddress", "ReceiverAddress")
                        .WithMany()
                        .HasForeignKey("ReceiverAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consignment_customer_address_receiver_address_id");

                    b.HasOne("Base.Entities.Consignment.Customer", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consignment_customer_receiver_id");

                    b.HasOne("Base.Entities.Consignment.CustomerAddress", "SenderAddress")
                        .WithMany()
                        .HasForeignKey("SenderAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consignment_customer_address_sender_address_id");

                    b.HasOne("Base.Entities.Consignment.Customer", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consignment_customer_sender_id");

                    b.Navigation("DestinationBranch");

                    b.Navigation("OriginBranch");

                    b.Navigation("RecBy");

                    b.Navigation("Receiver");

                    b.Navigation("ReceiverAddress");

                    b.Navigation("Sender");

                    b.Navigation("SenderAddress");
                });

            modelBuilder.Entity("Base.Entities.Consignment.ConsignmentStatusLog", b =>
                {
                    b.HasOne("Base.Entities.Consignment.Consignment", "Consignment")
                        .WithMany("StatusLogs")
                        .HasForeignKey("ConsignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consignment_status_log_consignment_consignment_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consignment_status_log_user_rec_by_id");

                    b.Navigation("Consignment");

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("Base.Entities.Consignment.Customer", b =>
                {
                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_user_rec_by_id");

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("Base.Entities.Consignment.CustomerAddress", b =>
                {
                    b.HasOne("Base.Entities.Consignment.Customer", "Customer")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_address_customer_customer_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_address_user_rec_by_id");

                    b.Navigation("Customer");

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("Base.Entities.Consignment.Package", b =>
                {
                    b.HasOne("Base.Entities.Consignment.Consignment", "Consignment")
                        .WithMany("Packages")
                        .HasForeignKey("ConsignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_package_consignment_consignment_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_package_user_rec_by_id");

                    b.Navigation("Consignment");

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("Base.Entities.Consignment.PickupTask", b =>
                {
                    b.HasOne("Base.Entities.Employee", "AssignedDriver")
                        .WithMany()
                        .HasForeignKey("AssignedDriverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pickup_task_employee_assigned_driver_id");

                    b.HasOne("Base.Entities.Vehicle", "AssignedVehicle")
                        .WithMany()
                        .HasForeignKey("AssignedVehicleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pickup_task_vehicle_assigned_vehicle_id");

                    b.HasOne("Base.Entities.Consignment.Consignment", "Consignment")
                        .WithMany("PickupTasks")
                        .HasForeignKey("ConsignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pickup_task_consignment_consignment_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pickup_task_user_rec_by_id");

                    b.Navigation("AssignedDriver");

                    b.Navigation("AssignedVehicle");

                    b.Navigation("Consignment");

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("Base.Entities.Driver", b =>
                {
                    b.HasOne("Base.Entities.Employee", "Employee")
                        .WithOne("Driver")
                        .HasForeignKey("Base.Entities.Driver", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_driver_employee_employee_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_driver_user_rec_by_id");

                    b.Navigation("Employee");

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("Base.Entities.Employee", b =>
                {
                    b.HasOne("Base.Entities.Branch", "CurrentBranch")
                        .WithMany()
                        .HasForeignKey("CurrentBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_branch_current_branch_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_user_rec_by_id");

                    b.HasOne("Base.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_employee_user_user_id");

                    b.Navigation("CurrentBranch");

                    b.Navigation("RecBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Base.Entities.Role", b =>
                {
                    b.HasOne("Base.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_branch_branch_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_rec_by_id");

                    b.Navigation("Branch");

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("Base.Entities.User", b =>
                {
                    b.HasOne("Base.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_branch_id");

                    b.HasOne("Base.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_user_created_by_id");

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Base.Entities.UserBranchTransfer", b =>
                {
                    b.HasOne("Base.Entities.Branch", "FromBranch")
                        .WithMany()
                        .HasForeignKey("FromBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_transfer_branch_from_branch_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_transfer_user_rec_by_id");

                    b.HasOne("Base.Entities.User", "RequestInitiator")
                        .WithMany()
                        .HasForeignKey("RequestInitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_transfer_user_request_initiator_id");

                    b.HasOne("Base.Entities.User", "Responder")
                        .WithMany()
                        .HasForeignKey("ResponderId")
                        .HasConstraintName("fk_user_branch_transfer_user_responder_id");

                    b.HasOne("Base.Entities.Branch", "ToBranch")
                        .WithMany()
                        .HasForeignKey("ToBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_transfer_branch_to_branch_id");

                    b.HasOne("Base.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_transfer_user_user_id");

                    b.Navigation("FromBranch");

                    b.Navigation("RecBy");

                    b.Navigation("RequestInitiator");

                    b.Navigation("Responder");

                    b.Navigation("ToBranch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Base.Entities.UserRole", b =>
                {
                    b.HasOne("Base.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_branch_branch_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_rec_by_id");

                    b.HasOne("Base.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_role_id");

                    b.HasOne("Base.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_user_id");

                    b.Navigation("Branch");

                    b.Navigation("RecBy");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Base.Entities.Vehicle", b =>
                {
                    b.HasOne("Base.Entities.Branch", "CurrentBranch")
                        .WithMany()
                        .HasForeignKey("CurrentBranchId")
                        .HasConstraintName("fk_vehicle_branch_current_branch_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_user_rec_by_id");

                    b.Navigation("CurrentBranch");

                    b.Navigation("RecBy");
                });

            modelBuilder.Entity("Base.Entities.VehicleAssignment", b =>
                {
                    b.HasOne("Base.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_assignment_employee_employee_id");

                    b.HasOne("Base.Entities.User", "RecBy")
                        .WithMany()
                        .HasForeignKey("RecById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_assignment_user_rec_by_id");

                    b.HasOne("Base.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleAssignments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_assignment_vehicle_vehicle_id");

                    b.Navigation("Employee");

                    b.Navigation("RecBy");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Base.Entities.Branch", b =>
                {
                    b.Navigation("PinCodes");
                });

            modelBuilder.Entity("Base.Entities.Consignment.Consignment", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("PickupTasks");

                    b.Navigation("StatusLogs");
                });

            modelBuilder.Entity("Base.Entities.Consignment.Customer", b =>
                {
                    b.Navigation("CustomerAddresses");
                });

            modelBuilder.Entity("Base.Entities.Employee", b =>
                {
                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Base.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Base.Entities.Vehicle", b =>
                {
                    b.Navigation("VehicleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
