<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
        <PackageReference Include="QRCoder" Version="1.7.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.3" />
        <PackageReference Include="EPPlus" Version="8.4.2" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Acl\Acl.csproj" />
      <ProjectReference Include="..\Base\Base.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\dist\jquery-confirm\jquery-confirm.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\jquery-confirm\jquery-confirm.min.js" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Role\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Role\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Role\Update.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\UserRole\AssignRole.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\AccountOpening\Views\ApplicationManagement\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\AccountOpening\Views\ApplicationManagement\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\AccountOpening\Views\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\AccountOpening\Views\_ViewStart.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Qb\Views\AccountGroup\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Qb\Views\AccountGroup\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Qb\Views\AccountGroup\New.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Qb\Views\BankGuaranteeType\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Qb\Views\BankGuaranteeType\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Qb\Views\BankGuarantee\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Qb\Views\BankGuarantee\GetQr.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Qb\Views\BankGuarantee\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Qb\Views\BankGuarantee\Update.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Qb\Views\BankGuarantee\ViewDoc.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Qb\Views\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Qb\Views\_ViewStart.cshtml" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\apexcharts.amd.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\apexcharts.common.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\apexcharts.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\apexcharts.esm.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\apexcharts.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\apexcharts.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\ar.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\ca.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\cs.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\de.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\el.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\en.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\es.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\et.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\fa.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\fi.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\fr.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\he.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\hi.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\hr.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\hu.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\hy.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\id.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\it.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\ja.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\ka.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\ko.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\lt.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\lv.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\nb.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\nl.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\pl.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\pt-br.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\pt.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\rs.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\ru.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\se.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\sk.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\sl.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\sq.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\th.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\tr.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\ua.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\zh-cn.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\apexcharts\dist\locales\zh-tw.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\bootstrap\dist\js\bootstrap.bundle.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\bootstrap\dist\js\bootstrap.bundle.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\bootstrap\dist\js\bootstrap.bundle.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\bootstrap\dist\js\bootstrap.bundle.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\bootstrap\dist\js\bootstrap.esm.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\bootstrap\dist\js\bootstrap.esm.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\bootstrap\dist\js\bootstrap.esm.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\bootstrap\dist\js\bootstrap.esm.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\bootstrap\dist\js\bootstrap.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\bootstrap\dist\js\bootstrap.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\bootstrap\dist\js\bootstrap.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\bootstrap\dist\js\bootstrap.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\countup.js\dist\countUp.d.ts" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\countup.js\dist\countUp.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\countup.js\dist\countUp.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\countup.js\dist\countUp.umd.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\countup.js\dist\requestAnimationFrame.polyfill.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\dropzone\dist\basic.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\dropzone\dist\basic.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\dropzone\dist\dropzone-min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\dropzone\dist\dropzone-min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\dropzone\dist\dropzone.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\dropzone\dist\dropzone.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\dropzone\dist\dropzone.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\dropzone\dist\dropzone.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\dropzone\dist\dropzone.mjs" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\dropzone\dist\dropzone.mjs.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\fslightbox\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\fslightbox\LICENSE" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\fslightbox\package.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\fslightbox\README.md" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\jsvectormap\dist\js\jsvectormap.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\jsvectormap\dist\js\jsvectormap.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\jsvectormap\dist\maps\world-merc.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\jsvectormap\dist\maps\world.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\list.js\dist\list.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\list.js\dist\list.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\list.js\dist\list.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\list.js\dist\list.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\bundle.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\css\litepicker.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\css\plugins\keyboardnav.js.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\css\plugins\mobilefriendly.js.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\css\plugins\multiselect.js.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\css\plugins\ranges.js.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\js\main.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\litepicker.amd.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\litepicker.commonjs2.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\litepicker.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\litepicker.umd.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\nocss\litepicker.amd.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\nocss\litepicker.commonjs2.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\nocss\litepicker.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\nocss\litepicker.umd.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\nocss\plugins\keyboardnav.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\nocss\plugins\mobilefriendly.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\nocss\plugins\multiselect.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\nocss\plugins\ranges.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\plugins\keyboardnav.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\plugins\mobilefriendly.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\plugins\multiselect.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\plugins\ranges.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\types\calendar.d.ts" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\types\core.d.ts" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\types\datetime.d.ts" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\types\index.d.ts" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\types\interfaces.d.ts" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\types\litepicker.d.ts" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\types\methods.d.ts" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\types\utils.d.ts" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\litepicker\dist\types\window.d.ts" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\nouislider\dist\nouislider.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\nouislider\dist\nouislider.d.ts" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\nouislider\dist\nouislider.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\nouislider\dist\nouislider.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\nouislider\dist\nouislider.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\nouislider\dist\nouislider.min.mjs" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\nouislider\dist\nouislider.mjs" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.min.mjs" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.min.mjs.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.mjs" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.polyfilled.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.polyfilled.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.polyfilled.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.polyfilled.min.mjs" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.polyfilled.min.mjs.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.polyfilled.mjs" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\plyr\dist\plyr.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\star-rating.js\dist\star-rating.cjs.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\star-rating.js\dist\star-rating.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\star-rating.js\dist\star-rating.esm.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\star-rating.js\dist\star-rating.esm.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\star-rating.js\dist\star-rating.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\star-rating.js\dist\star-rating.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\star-rating.js\dist\star-rating.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\bower.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\CHANGELOG.md" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\composer.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\icons\default\icons.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\icons\default\icons.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\icons\default\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\license.txt" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\models\dom\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\models\dom\model.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\models\dom\model.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\package.json" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\advlist\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\advlist\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\advlist\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\anchor\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\anchor\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\anchor\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\autolink\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\autolink\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\autolink\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\autoresize\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\autoresize\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\autoresize\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\autosave\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\autosave\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\autosave\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\charmap\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\charmap\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\charmap\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\codesample\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\codesample\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\codesample\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\code\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\code\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\code\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\directionality\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\directionality\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\directionality\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\emoticons\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\emoticons\js\emojiimages.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\emoticons\js\emojiimages.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\emoticons\js\emojis.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\emoticons\js\emojis.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\emoticons\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\emoticons\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\fullscreen\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\fullscreen\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\fullscreen\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\help\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\help\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\help\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\image\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\image\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\image\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\importcss\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\importcss\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\importcss\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\insertdatetime\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\insertdatetime\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\insertdatetime\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\link\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\link\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\link\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\lists\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\lists\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\lists\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\media\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\media\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\media\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\nonbreaking\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\nonbreaking\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\nonbreaking\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\pagebreak\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\pagebreak\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\pagebreak\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\preview\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\preview\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\preview\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\quickbars\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\quickbars\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\quickbars\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\save\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\save\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\save\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\searchreplace\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\searchreplace\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\searchreplace\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\table\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\table\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\table\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\template\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\template\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\template\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\visualblocks\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\visualblocks\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\visualblocks\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\visualchars\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\visualchars\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\visualchars\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\wordcount\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\wordcount\plugin.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\plugins\wordcount\plugin.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\README.md" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\content\dark\content.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\content\dark\content.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\content\default\content.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\content\default\content.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\content\document\content.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\content\document\content.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\content\tinymce-5-dark\content.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\content\tinymce-5-dark\content.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\content\tinymce-5\content.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\content\tinymce-5\content.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\content\writer\content.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\content\writer\content.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide-dark\content.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide-dark\content.inline.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide-dark\content.inline.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide-dark\content.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide-dark\skin.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide-dark\skin.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide-dark\skin.shadowdom.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide-dark\skin.shadowdom.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide\content.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide\content.inline.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide\content.inline.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide\content.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide\skin.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide\skin.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide\skin.shadowdom.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\oxide\skin.shadowdom.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5-dark\content.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5-dark\content.inline.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5-dark\content.inline.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5-dark\content.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5-dark\skin.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5-dark\skin.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5-dark\skin.shadowdom.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5-dark\skin.shadowdom.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5\content.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5\content.inline.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5\content.inline.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5\content.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5\skin.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5\skin.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5\skin.shadowdom.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\skins\ui\tinymce-5\skin.shadowdom.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\themes\silver\index.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\themes\silver\theme.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\themes\silver\theme.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\tinymce.d.ts" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\tinymce.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tinymce\tinymce.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\caret_position.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\caret_position.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\change_listener.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\change_listener.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\checkbox_options.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\checkbox_options.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\clear_button.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\clear_button.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\drag_drop.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\drag_drop.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\dropdown_header.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\dropdown_header.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\dropdown_input.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\dropdown_input.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\input_autogrow.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\input_autogrow.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\no_active_items.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\no_active_items.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\no_backspace_delete.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\no_backspace_delete.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\optgroup_columns.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\optgroup_columns.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\remove_button.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\remove_button.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\restore_on_backspace.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\restore_on_backspace.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\virtual_scroll.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\plugins\virtual_scroll.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\tom-select.base.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\tom-select.base.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\tom-select.base.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\tom-select.base.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\tom-select.complete.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\tom-select.complete.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\tom-select.complete.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\tom-select.complete.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\tom-select.popular.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\tom-select.popular.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\tom-select.popular.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\dist\libs\tom-select\dist\js\tom-select.popular.min.js.map" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\UserBranchTransfer\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\UserBranchTransfer\RequestTransfer.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Areas\Acl\Views\Role\Create.cshtml" />
      <AdditionalFiles Include="Areas\Acl\Views\Role\Index.cshtml" />
      <AdditionalFiles Include="Areas\Acl\Views\Role\Update.cshtml" />
      <AdditionalFiles Include="Areas\Acl\Views\UserRole\AssignRole.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations\" />
      <Folder Include="wwwroot\dist\libs\" />
    </ItemGroup>

</Project>
